name: dependency-review

on:
  - pull_request_target

jobs:
  shared:
    uses: amezin/js-actions-common/.github/workflows/shared-dependency-review.yml@57d51f58d78c08e511c26da2c5ddfbba693e5eeb # v2.0.3
    permissions:
      contents: read
      pull-requests: write
